version: '3.8'

services:
  gateway:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.services.gateway.loadbalancer.server.port=3001"
    ports:
      - "3001:3001" # Optional for dev
    volumes:
      - .:/app
    depends_on:
      - traefik

  traefik:
    image: traefik:v3.0
    command:
      - --providers.docker=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8080
      - --log.level=INFO
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.entrypoints=traefik"
      - "traefik.http.routers.traefik.service=api@internal"