version: '3.8'

services:
  gateway:
    build:
      context: ./gateway-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls=true"
      - "traefik.http.routers.gateway.tls.certresolver=devhttps"
      - "traefik.http.services.gateway.loadbalancer.server.port=3001"
    volumes:
      - ./gateway-server:/app
    depends_on:
      - traefik
    ports:
      - "3001:3001" # Optional for local dev access

  rag-engine:
    build:
      context: ../api/rag-engine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag.rule=PathPrefix(`/rag`)"
      - "traefik.http.routers.rag.entrypoints=websecure"
      - "traefik.http.routers.rag.tls=true"
      - "traefik.http.routers.rag.tls.certresolver=devhttps"
      - "traefik.http.services.rag.loadbalancer.server.port=4000"
    ports:
      - "4000:4000"
    depends_on:
      - traefik

  session-server:
    build:
      context: ../api/session-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.session.rule=PathPrefix(`/session`)"
      - "traefik.http.routers.session.entrypoints=websecure"
      - "traefik.http.routers.session.tls=true"
      - "traefik.http.routers.session.tls.certresolver=devhttps"
      - "traefik.http.services.session.loadbalancer.server.port=4001"
    ports:
      - "4001:4001"
    depends_on:
      - traefik

  traefik:
    image: traefik:v3.0
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --api.dashboard=true
      - --log.level=INFO
      - --certificatesresolvers.devhttps.acme.tlschallenge=true
      - --certificatesresolvers.devhttps.acme.email=test@example.com
      - --certificatesresolvers.devhttps.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./traefik/certs:/letsencrypt