apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-server
  template:
    metadata:
      labels:
        app: session-server
    spec:
      containers:
        - name: session-server
          image: session-server:latest
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 20