# .github/workflows/jiode-pages.yml
name: pages-jiode.one

on:
  push:
    branches: [main]
    paths:
      - "apps/core/portfolio/jiode.one/**"
  pull_request:
    paths:
      - "apps/core/portfolio/jiode.one/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_VERSION: 20
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack (uses package.json packageManager)
        run: corepack enable

      # If jiode.one needs deps, install them **scoped** to just that app
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - uses: pnpm/action-setup@v4


      # If you keep a root lockfile, build via Nx filtered to that app:
      - run: pnpm -w --filter "apps/core/portfolio/jiode.one/" install --frozen-lockfile
      - run: pnpm -w --filter "@jiode/jiode.one" run build

      # Deploy via Cloudflare Pages action
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jiode-one              # Pages project name
          directory: dist/apps/jiode.one      # folder that build produced
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # For production deploys only on main:
          branch: ${{ github.ref_name }}
