name: sesame PR Checks & preview
env:
  APP_ID: sesame.jiode.one
  APP_PATH: apps/core/portfolio/sesame.jiode.one
  PUBLIC_DIR: apps/core/portfolio/sesame.jiode.one/public
  WRANGLER_CONFIG: apps/core/portfolio/sesame.jiode.one/sesame-meta-worker/wrangler.preview.toml
  PREVIEW_BUCKET: sesame-data-preview
  PREVIEW_HOST: ${{ vars.PREVIEW_HOST || 'preview.sesame.jiode.one' }}

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/core/portfolio/sesame.jiode.one/**'
      - '.github/workflows/**'


permissions:
  contents: read
  deployments: write

concurrency:
  group: pr-sesame-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verify:
    name: sesame / verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - name: Enable Corepack (uses package.json packageManager)
        run: corepack enable
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile

      # Add whatever is relevant/fast for this worker
      - name: Type check (tsc --noEmit)
        run: pnpm -w exec tsc -p ${{ env.APP_PATH }}/tsconfig.json --noEmit || true

      - name: Lint
        run: pnpm -w exec eslint ${{ env.APP_PATH }} --max-warnings=0 || true

      - name: Unit tests (if you have any)
        run: pnpm -w test --filter @jiode/sesame || echo "no tests yet"


  ci:
    uses: ./.github/workflows/_worker-ci.yml
    with:
      app_id:          ${{ env.APP_ID }}
      app_path:        ${{ env.APP_PATH }}
      wrangler_config: ${{ env.WRANGLER_CONFIG }}
      environment:     preview
      deploy:          false  # just build in CI job
    secrets: {}

  preview:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    needs: ci
    uses: ./.github/workflows/_worker-ci.yml
    with:
      app_id:          ${{ env.APP_ID }}
      app_path:        ${{ env.APP_PATH }}
      wrangler_config: ${{ env.WRANGLER_CONFIG }}
      environment:     preview
      deploy:          true
      worker_name:     sesame-pr-${{ github.event.pull_request.number }}
      preview_host:  ${{ env.PREVIEW_HOST }}
    secrets:
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  mark-deployment:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mark Deployment Preview
        uses: ./.github/actions/mark-deployment/mark-deployment-preview

