name: Promote to Prod

on:
  workflow_dispatch:
    inputs:
      release_sha:
        description: "Commit SHA to promote (must match an uploaded staging artifact)"
        required: true
      confirm:
        description: 'Type "I understand" to deploy to prod'
        required: true

concurrency:
  group: ${{ github.workflow }}-prod
  cancel-in-progress: false

permissions:
  contents: read
  actions: read

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "I understand" ]; then
            echo "Confirmation mismatch. Aborting."; exit 1; fi
      - name: Echo release SHA
        run: echo "Promoting ${{ github.event.inputs.release_sha }}"

  deploy:
    needs: preflight
    runs-on: ubuntu-latest
    # Protect prod via GitHub Environments (branch protection / required reviewers)
    environment: production
    env:
      NODE_VERSION: '20'
      NX_CLOUD_DISABLED: 'true'
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v4
      # We don't rebuild; we re-use the exact staging artifact
      - name: Download staging artifact for this SHA
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: wearejiode/one
          workflow: Release to Staging
          workflow_conclusion: success
          name: sesame-worker-${{ inputs.release_sha }}
          search_artifacts: true
          name_is_regexp: false
          path: dist/releases/${{ inputs.release_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify artifact exists
        run: |
          test -f "dist/releases/${{ github.event.inputs.release_sha }}/meta-worker.generated.js" \
            || (echo "Artifact missing for SHA" && exit 1)

      # Optional: ensure prod R2 exists (idempotent)
      - name: Ensure R2 bucket (prod, idempotent)
        shell: bash
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler r2 bucket create sesame-data --remote >/dev/null 2>&1 || true

      # Optional: seed data.json only if missing
      - name: Check data.json in prod
        id: r2-head
        shell: bash
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          if npx wrangler r2 object get sesame-data/data.json --remote > /dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Seed data.json to prod (first-time only)
        if: steps.r2-head.outputs.exists == 'false'
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.31.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            r2 object put sesame-data/data.json
            --file apps/core/portfolio/sesame.jiode.one/data.json

      # Optional: sync prod images folder (only new/changed)
      # Comment out if you prefer manual management.
# Optional: sync prod images (public/**/* -> images/*)
      - name: Upload public/* to prod R2
        shell: bash
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          set -euo pipefail
          BASE="apps/core/portfolio/sesame.jiode.one/public"
          if [ -d "$BASE" ]; then
            find "$BASE" -type f -print0 | while IFS= read -r -d '' f; do
              key="images/${f#$BASE/}"
              ctype=$(file --mime-type -b "$f" || echo application/octet-stream)
              echo "→ R2 put sesame-data/$key"
              npx wrangler r2 object put "sesame-data/$key" --file "$f" --content-type "$ctype" --remote
            done
          else
            echo "No $BASE folder found — skipping image upload."
          fi

      # Deploy to prod (no bundle, use prod wrangler.toml)
      - name: Deploy to production
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.31.0'
          command: >
            deploy dist/releases/${{ github.event.inputs.release_sha }}/meta-worker.generated.js
            --config apps/core/portfolio/sesame.jiode.one/sesame-meta-worker/wrangler.toml
            --no-bundle

  # (Optional) quick rollback using a version id
  rollback:
    if: ${{ false }} # flip to true when you want to run via "Re-run job" with inputs
    runs-on: ubuntu-latest
    needs: deploy
    environment: production
    steps:
      - name: Rollback (example)
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.31.0'
          command: >
            rollback
