name: Release to Staging

on:
  push:
    branches: [main]
    paths:
      - 'apps/core/portfolio/sesame.jiode.one/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

# Ensure only one staging release runs per ref at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_VERSION: '20'
      NX_CLOUD_DISABLED: 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Bundle worker
        run: pnpm -w nx run sesame.jiode.one:bundle-worker --cloud=false

      - name: Archive artifact (by commit SHA)
        run: |
          mkdir -p dist/releases/${{ github.sha }}
          cp dist/apps/sesame.jiode.one/meta-worker.generated.js dist/releases/${{ github.sha }}/meta-worker.generated.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sesame-worker-${{ github.sha }}
          path: dist/releases/${{ github.sha }}/meta-worker.generated.js
          if-no-files-found: error
          retention-days: 30

      - name: Ensure R2 bucket (staging)
        uses: cloudflare/wrangler-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          command: |
            wrangler r2 bucket create sesame-data-staging || exit 0

      # Seed data.json only if missing (avoid clobbering)
      - name: Seed data.json if absent
        uses: cloudflare/wrangler-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          command: |
            wrangler r2 object head sesame-data-staging/data.json >/dev/null 2>&1 \
            || wrangler r2 object put sesame-data-staging/data.json \
                 --file apps/core/portfolio/sesame.jiode.one/data.json

      - name: Deploy to staging
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} # repo secret
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # repo secret
          command: >
            deploy dist/releases/${{ github.sha }}/meta-worker.generated.js
            --config apps/core/portfolio/sesame.jiode.one/sesame-meta-worker/wrangler.staging.toml
            --no-bundle
